config/routes.rb
Rails.application.routes.draw do
  # Configurar  MercadoPago
  post 'mercadopago_checkout', to: 'campania_donacions#realizar_pago'
  post 'webhooks', to: 'campania_donacions#actualizar_donacion'

  resources :campania_donacions
  resources :campania

  resources :vet_de_guardia
  resources :historia_clinicas
  resources :ambulatoria
  resources :desparasitacions
  resources :vacuna_rs
  resources :vacuna_es
  resources :castracions
  resources :historia_cs
  resources :perros_que_buscan_parejas

  resources :perros_en_adopcions

  resources :turnos
  get  'turnos', to: 'turnos#index'
  post 'turnos/generar', to: 'turnos#generar', as: 'generar_turno'
  post 'turnos/rechazar', to: 'turnos#rechazar', as: 'rechazar_turno'
  post 'turnos/cancelar-v', to: 'turnos#cancelar_veterinario', as: 'cancelar_turno_veterinario'
  post 'turnos/cancelar-c', to: 'turnos#cancelar_cliente', as: 'cancelar_turno_cliente'
  delete 'turnos', to: 'turnos#destroy'

  root 'home#index'

  devise_for :users, path_prefix: 'my', controllers: {
    registrations: 'users/registrations'
  }
 # devise_for :users,: :path_prefix => 'my'
  resources :users, only: [:index, :atencion]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'perfil', to: 'users#ver_perfil'
    get 'edit_user', to: 'users/registrations#edit'
    patch 'update_user_registration', to: 'users/registrations#update'
  end
  resources :users do
    collection do
      get 'atencion'
    end
  resources :users do
    member do
      get 'agregar_perrito'
      post 'crear_perrito'
    end
  end
  resources :users do
    resources :perritos # Esto anida las rutas de perritos dentro de las rutas de usuarios
  end


  get 'profile/edit', to: 'profile#edit', as: :edit_profile
  end

  #Creacion de usuario del veterinario
  get 'creacion_usuario', to: 'users/registro#new', as: 'creacion_usuario'
  post 'creacion_usuario', to: 'users/registro#create'

  #Atencion al cliente
  get 'perrito_ajeno/:id', to: 'perritos#new_ajeno', as: 'perrito_ajeno'
  get 'edit_other/:id', to: 'users#edit_otro', as: 'edit_other'
  get 'usuarios/:id', to: 'users#ver_perfil'
  get '/perfil/:id', to: 'users#ver_perfil', as: 'ver_perfil'
  get 'atencion_cliente', to: 'users#atencion'

  #Interfaz de los perros
  get 'show_perrito/:id', to: 'perritos#show', as: 'show_perrito'
  get 'add_dog.:id', to: 'perritos#new', as: 'add_dog'
  get 'marcar_fallecido/:id', to: 'perritos#marcar_fallecido', as: 'marcar_fallecido'
  resources :perritos do
    member do
      patch 'marcar_fallecido'
    end
  end
  #Historia clinica del perro
  get 'ver_perrito/:id', to: 'perritos#ver', as: 'ver_perrito'
  get 'ver_perrito_ajeno/:id', to: 'perritos#ver_ajeno', as: 'ver_perrito_ajeno'
  get 'crear_historia/:id', to: 'perritos#agregar_historia', as: 'crear_historia'
  get 'crear_castracion/:id', to: 'historia_clinicas#new_castracion', as: 'crear_castracion'
  get 'crear_vacunae/:id', to: 'historia_clinicas#new_vacunae', as: 'crear_vacunae'
  get 'crear_vacunar/:id', to: 'historia_clinicas#new_vacunar', as: 'crear_vacunar'
  get 'crear_desparasitacion/:id', to: 'historia_clinicas#new_desparasitacion', as: 'crear_desparasitacion'
  get 'crear_atencion_clinica/:id', to: 'historia_clinicas#new_atencion_clinica', as: 'crear_atencion_clinica'
  get 'ver_castracion/:id', to: 'historia_clinicas#ver_castracion', as: 'ver_castracion'
  get 'ver_desparasitacion/:id', to: 'historia_clinicas#ver_desparasitacion', as: 'ver_desparasitacion'
  get 'ver_vacunar/:id', to: 'historia_clinicas#ver_vacunar', as: 'ver_vacunar'
  get 'ver_vacunae/:id', to: 'historia_clinicas#ver_vacunae', as: 'ver_vacunae'
  get 'ver_atencion/:id', to: 'historia_clinicas#ver_atencion', as: 'ver_atencion'
  resources :historia_clinicas do
    post 'create_vacunar', on: :collection
    post 'create_vacunae', on: :collection
  end

  #Envio de mail de joaco
  post '/random_password_email', to: 'user_mailer#random_password_email'

  #Campañas de donacion
  get 'ver_campanias', to: 'campania_donacions#index', as: 'ver_campanias'
  get 'cargar_campania', to: 'campania_donacions#cargar', as: 'cargar_campania'
  get 'eliminar_campania', to: 'campania_donacions#destroy', as: 'eliminar_campania'
  get 'editar_campania/:id', to: 'campania_donacions#editar', as: 'editar_campania'
  resources :campanias do
    post 'crear_campania', on: :collection
    resources :campania_donacions, only: [:destroy]
  end


  resources :cuidador_paseadors, path: 'cuidadores-y-paseadores'
  resources :perros_perdidos, path: 'se-busca'

  resources :perros_encontrados do
    collection do
      get 'edit_no_registrado'
    end
  end

  resources :perros_encontrados
  resources :perritos

  patch '/perros_perdidos/:id/marcar_como_encontrado', to: 'perros_perdidos#marcar_como_encontrado', as: :marcar_como_encontrado_perros_perdido
  patch '/perros_encontrados/:id/marcar_como_dueno_encontrado', to: 'perros_encontrados#marcar_como_dueno_encontrado', as: :marcar_como_dueno_encontrado_perros_encontrado
  patch '/perros_en_adopcion/:id/marcar_como_adoptado', to: 'perros_en_adopcions#marcar_como_adoptado', as: :marcar_como_adoptado_perros_en_adopcion

  #mails javi
  post '/enviar_correo', to: 'cuidador_paseadors#enviar_correo'
  post '/enviar_correo_no_registrado', to: 'cuidador_paseadors#enviar_correo_no_registrado'

  post '/enviar_correo_perros_perdidos', to: 'perros_perdidos#enviar_correo_perros_perdidos'
  post '/enviar_correo_perros_encontrados', to: 'perros_encontrados#enviar_correo_perros_encontrados'
  post '/enviar_correo_perros_encontrados_no_registrado', to: 'perros_encontrados#enviar_correo_perros_encontrados_no_registrado'

  resources :perros_encontrados do
    member do
      post 'enviar_correo_perros_encontrados_no_registrado'
    end
  end

 # config/routes.rb
get '/perros_encontrados/edit_no_registrado', to: 'perros_encontrados#edit_no_registrado', as: 'edit_no_registrado_perros_encontrado'








  post '/enviar_correo_perros_perdidos_contactar', to: 'perros_perdidos#enviar_correo_perros_perdidos_contactar'
  post '/enviar_correo_perros_encontrados_contactar', to: 'perros_encontrados#enviar_correo_perros_encontrados_contactar'
  post '/enviar_correo_contactar_registrado', to: 'perros_en_adopcions#enviar_correo_contactar_registrado'
  post '/enviar_correo_contactar_no_registrado', to: 'perros_en_adopcions#enviar_correo_contactar_no_registrado'

  resources :perros_que_buscan_parejas do
    post 'postular', on: :member
    post 'retirar', on: :member
    get 'buscar_pareja', on: :member
    post 'me_gusta', on: :member
    post 'no_me_gusta', on: :member
    post 'ya_no_me_gusta', on: :member
    get 'ver_mis_no_me_gusta', on: :member
    post 'retirar_no_me_gusta', on: :member
    get 'ver_perros_que_me_dieron_me_gusta', on: :member
    get 'ver_los_matcheos_de_mi_perro', on: :member
  end


end

app/models/perros_perdido.rb
class PerrosPerdido < ApplicationRecord
    attr_accessor :action_type

    has_one_attached :foto

    validates :foto, presence: { message: "Debe subir una foto" }

    validate :foto_content_type
    validate :nombre_unico_para_usuario_actual
    validate :nombre_sin_caracteres_especiales

    def foto_content_type
      if foto.attached? && !foto.content_type.in?(%w(image/jpeg image/jpg image/png image/gif image/webp))
        errors.add(:foto, 'El formato de imagen no es válido.')
      end
    end

    def nombre_unico_para_usuario_actual
      if action_type == 'create'
        if PerrosPerdido.exists?(nombre: nombre, mail: mail, status: 'Se busca')
          errors.add(:nombre, "Ya tienes una publicacion con este nombre de perro!")
        end
      else
        existing_perro = PerrosPerdido.find_by(nombre: nombre, mail: mail, status: 'Se busca')
        if existing_perro && existing_perro.id != id
          errors.add(:nombre, "Ya tienes una publicacion con este nombre de perro!")
        end
      end
    end

    def nombre_sin_caracteres_especiales
      if nombre.present? && nombre.match(/[^A-Za-z]/)
        errors.add(:nombre, 'El nombre solo puede contener letras y sin espacios.')
      end
    end
    

end

app/controllers/perros_perdidos_controller.rb
class PerrosPerdidosController < ApplicationController
  before_action :set_perros_perdido, only: %i[ update show edit destroy ]

  # GET /perros_perdidos or /perros_perdidos.json
  def index

    @all_dogs = PerrosPerdido.all

    if params[:filter].present?
      perros_perdidos = PerrosPerdido.where(mail: params[:filter], status: 'Se busca').order(created_at: :desc)
      perros_encontrados = PerrosPerdido.where(mail: params[:filter], status: 'Encontrado').limit(50).order(created_at: :asc)

      # Combinar perros perdidos y encontrados
      @perros = perros_perdidos + perros_encontrados

      # Ordenar la lista combinada por status y fecha de forma descendente
      @perros = @perros.sort_by { |perro| [perro.status.downcase, perro.created_at] }.reverse

      # Aplicar paginación a la lista
      @perros = Kaminari.paginate_array(@perros).page(params[:page]).per(3)
    else
      perros_perdidos = PerrosPerdido.where(status: 'Se busca').order(created_at: :desc)
      perros_encontrados = PerrosPerdido.where(status: 'Encontrado').limit(50).order(created_at: :asc)

      # Combinar perros perdidos y encontrados
      @perros = perros_perdidos + perros_encontrados

      # Ordenar la lista combinada por status y fecha de forma descendente
      @perros = @perros.sort_by { |perro| [perro.status.downcase, perro.created_at] }.reverse

      # Aplicar paginación a la lista
      @perros = Kaminari.paginate_array(@perros).page(params[:page]).per(3)
    end

    @users = User.all

  end


  # GET /perros_perdidos/1 or /perros_perdidos/1.json
  def show
  end

  # GET /perros_perdidos/new
  def new
    @perros_perdido = PerrosPerdido.new
  end

  # GET /perros_perdidos/1/edit
  def edit
  end

  # POST /perros_perdidos or /perros_perdidos.json
  def create
    @perros_perdido = PerrosPerdido.new(perros_perdido_params)
    @perros_perdido.action_type = 'create'
    respond_to do |format|
      if @perros_perdido.save
        format.html { redirect_to perros_perdidos_path, notice: "El perro se ha publicado exitosamente!" }
        format.json { render :show, status: :created, location: @perros_perdido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @perros_perdido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perros_perdidos/1 or /perros_perdidos/1.json
  def update
    @perros_perdido.action_type = 'update'
    respond_to do |format|
      if @perros_perdido.update(perros_perdido_params)
        format.html { redirect_to perros_perdidos_path, notice: "La publicación ha sido editada correctamente!" }
        format.json { render :show, status: :ok, location: @perros_perdido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @perros_perdido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perros_perdidos/1 or /perros_perdidos/1.json
  def destroy
    @perros_perdido.destroy!

    respond_to do |format|
      format.html { redirect_to perros_perdidos_path, notice: "La publicacion ha sido eliminada correctamente!" }
      format.json { head :no_content }
    end
  end

  def marcar_como_encontrado

    @perros_perdido = PerrosPerdido.find(params[:id])
    if @perros_perdido.update(status: 'Encontrado')
      redirect_to perros_perdidos_path, notice: 'El perro ha sido marcado como encontrado.'
    else
      redirect_to perros_perdidos_path, alert: 'No se pudo marcar el perro como encontrado.'
    end

  end

  def enviar_correo_perros_perdidos

    id = params[:id]
    @perro = PerrosPerdido.find(id)

    @owner = User.find_by(email: @perro.mail)

    @current_user = current_user

    PerrosPerdidosMailer.enviar_correo_perros_perdidos(@perro, @owner, @current_user).deliver_later

    respond_to do |format|
      format.html { redirect_to perros_perdidos_path, flash: { notice: "El correo fue enviado con exito." } }
      format.json { head :no_content }
    end

  end

  def enviar_correo_perros_perdidos_contactar

    id = params[:id]
    @perro = PerrosPerdido.find(id)

    @owner = User.find_by(email: @perro.mail)

    nombre = params[:nombre]
    apellido = params[:apellido]
    direccion = params[:direccion]
    numero = params[:numero]
    email = params[:email]

    existing_user = User.find_by(email: params[:email])

    if existing_user || (email == @perro.mail)
      # El correo electrónico ya está registrado, realiza alguna acción (por ejemplo, mostrar un mensaje de error)
      flash[:alert] = "El correo electrónico ya está registrado en la veterinaria o estas intentando contactarrte a ti mismo"
      redirect_back(fallback_location: perros_perdidos_path) # Puedes redirigir a donde desees
    else
      PerrosPerdidosMailer.enviar_correo_perros_perdidos_contactar(@perro, @owner, nombre, apellido, direccion, numero, email).deliver_later

      respond_to do |format|
        format.html { redirect_to perros_perdidos_path, flash: { notice: "El correo fue enviado con exito." } }
        format.json { head :no_content }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perros_perdido
      @perros_perdido = PerrosPerdido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def perros_perdido_params
      params.require(:perros_perdido).permit(:nombre, :foto, :fecha_de_publicacion, :status, :descripcion, :mail, :raza, :edad_aproximada, :tamano, :lugar_zona_donde_se_encontro)
    end



end

app/helpers/perros_perdidos_helper.rb
module PerrosPerdidosHelper
end

app/views/perros_perdidos/_perros_perdido.html.erb
<div id="<%= dom_id perros_perdido %>">
  
  <p>
    <%= image_tag(perros_perdido.foto, class: 'img-thumbnail', style: 'height: 200px; width: 200px;') %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= perros_perdido.nombre %>
  </p>

  <p>
    <strong>descripcion:</strong>
    <%= perros_perdido.descripcion %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= perros_perdido.status %>
  </p>

  <p>
    <strong>Fecha de publicacion:</strong>
    <%= perros_perdido.fecha_de_publicacion.strftime("%d/%m/%y") %>
  </p>

<!--
  <p>
    <strong>mail:</strong>
    <%= perros_perdido.mail %>
  </p>
-->

</div>

app/views/perros_perdidos/edit.html.erb
<h1>Editar perro perdido</h1>


<%= render "form", perros_perdido: @perros_perdido %>

app/views/perros_perdidos/index.html.erb
<h1>Perros perdidos</h1>


<% if user_signed_in? %>
  <a href="<%= new_perros_perdido_path %>" class="btn btn-turqueza">Publicar un perro perdido</a>
  <%= link_to "Perros perdidos", perros_perdidos_path , class: "btn btn-turqueza perros-encontrados-boton" %>
  <%= link_to "Mis perros perdidos", perros_perdidos_path(filter: current_user.email) , class: "btn btn-turqueza mis-perros-encontrados-boton" %>
<% end %>

<% if @all_dogs.empty? %>
  <div class="no_mis_perros">
    <p>No hay publicaciones de perros perdidos en busqueda activa, te invitamos a que publiques si encontraste un perro para que se reencuentre con su dueño.</p>
  </div>
<% end %>

<% if user_signed_in? && @all_dogs.none? { |perro| perro.mail == current_user.email }   %>
  <div class="mis_perros">
    <p>No tienes publicaciones de perros perdidos.</p>
  </div>
<% end %>

<div class= 'd-flex flex-wrap'>

  <% @perros.each do |perros| %>
   
    <div class="<%= (user_signed_in? && current_user.email == perros.mail) ? '' : 'no_mis_perros' %> card d-flex" style="max-width: 350px; max-height: 650px; min-width: 350px; min-height: 500px; margin: 10px">
     
      <%= image_tag(perros.foto, class:'card-img-top', style:'max-height: 200px; min-height: 200px; max-width: 100%; object-fit: cover;  object-position: top; ') %>
      <div class="card-body">
        <p class="card-text", style=''> <strong> Nombre: </strong> <%= perros.nombre %> </p>
        <p id=ci class="card-text" style="max-height: 100px; overflow: hidden;"> <strong> Descripcion: </strong> <%= perros.descripcion %> </p>
        <p class="card-text", style=''> <strong> Raza: </strong> <%= perros.raza %> </p>
        <p class="card-text", style=''> <strong> Edad aproximada: </strong> <%= perros.edad_aproximada %> </p>
        <p class="card-text", style=''> <strong> Tamaño: </strong> <%= perros.tamano %> </p>
        <p class="card-text", style=''> <strong> Lugar/zona donde se perdio: </strong> <%= perros.lugar_zona_donde_se_encontro %> </p>
        <p class="card-text"> <strong> Estado: </strong><%= perros.status %> </p>
        <p class="card-text"> <strong> Fecha de publicacion: </strong><%= perros.fecha_de_publicacion.strftime("%d/%m/%y") %> </p>
      </div>


      <div class='d-flex justify-content-center' style='flex-direction: column; align-items: center;'>
        <% if (!user_signed_in? || (user_signed_in? && current_user.email != perros.mail)) && perros.status == 'Se busca' %>
          <div>
            <button type="button"  class = "btn btn-turqueza" style = 'margin-bottom: 3px' data-bs-toggle="modal" data-bs-target="<%= (user_signed_in?) ? "#ModalPedirServiciosRegistrado-#{perros.id}" : "#ModalPedirServiciosNoRegistrado-#{perros.id}" %>" >Contactar</button>

            <!-- Modal Pedir Servicios Registrado-->
            <div class="modal fade" id="ModalPedirServiciosRegistrado-<%= perros.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Enviar datos de contacto</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <p>Se le enviara un email a <%= @users.find_by(email: perros.mail).nombre %> <%= @users.find_by(email: perros.mail).apellido %> para informarle que has encontrado a este perro.</p>
                    <p>Este incluira la siguiente informacion de su cuenta:</p>
                    <ul>
                      <li>Nombre</li>
                      <li>Apellido</li>
                      <li>Direccion</li>
                      <li>Numero</li>
                      <li>Direccion de correo electronico</li>
                    </ul>
                    <p>Pronto <%= @users.find_by(email: perros.mail).nombre %> <%= @users.find_by(email: perros.mail).apellido %> se comunicara con usted.</p>
                  </div>
                  <div class="modal-footer">
                    <%= link_to "Enviar", enviar_correo_perros_perdidos_path(id: perros.id), data: { turbo_method: :post },  class: "btn btn-turqueza", style:'margin: 2px' %>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Atras</button>
                  </div>
                </div>
              </div>
            </div>

            <!-- Modal Pedir Servicios No Registrado-->
            <div class="modal fade" id="ModalPedirServiciosNoRegistrado-<%= perros.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Enviar datos de contacto</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <p>Se le enviara un email a <%= @users.find_by(email: perros.mail).nombre %> <%= @users.find_by(email: perros.mail).apellido %> para informarle que has encontrado a este perro.</p>
                    <p>Completa este formulario con tu informacion para que pueda contactarte:</p>
                    <%= form_with url: enviar_correo_perros_perdidos_contactar_path(id: perros.id), method: :post, id: 'formularioDatos' do |form| %>
                        
                      <div class="mb-3">
                        <%= form.label :nombre, 'Nombre:' %>
                        <%= form.text_field :nombre, class: 'form-control', required: true %>
                      </div>

                      <div class="mb-3">
                        <%= form.label :apellido, 'Apellido:' %>
                        <%= form.text_field :apellido, class: 'form-control', required: true %>
                      </div>

                      <div class="mb-3">
                        <%= form.label :direccion, 'Dirección:' %>
                        <%= form.text_field :direccion, class: 'form-control', required: true %>
                      </div>

                      <div class="mb-3">
                        <%= form.label :numero, 'Número:' %>
                        <%= form.text_field :numero, class: 'form-control', required: true %>
                      </div>

                      <div class="mb-3">
                        <%= form.label :email, 'Correo electrónico:' %>
                        <%= form.email_field :email, class: 'form-control', required: true %>
                      </div>

                      <%= form.submit 'Enviar', id: "confirmarBtn", class: 'btn btn-success', style:"margin: 2px" %>
                      <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Atras</button>
                    <% end %>

                  </div>
                </div>
              </div>
            </div>

          </div>
        <% else %>
          <% if user_signed_in? && current_user.email == perros.mail && perros.status == 'Se busca'%>
            <div class='d-flex align-items-end'>
              <%= link_to "Editar", edit_perros_perdido_path(perros) , class: "btn btn-secondary", style:'margin: 2px' %>
              <button type="button" class="btn btn-danger" style='margin: 2px' data-bs-toggle="modal" data-bs-target="#ModalEliminar-<%= perros.id %>">Eliminar</button>
            </div>


            <!-- Modal Eliminar-->
            <div class="modal fade" id="ModalEliminar-<%= perros.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar Publicacion</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    Desea eliminar la publicacion de este perro perdido de forma permanente ?
                  </div>
                  <div class="modal-footer">
                    <%= link_to "Confirmar", perros, data: { turbo_method: :delete } ,  class: "btn btn-turqueza", style:'margin: 2px' %>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Atras</button>
                  </div>
                </div>
              </div>
            </div>


            <div>
              <%= button_to "Marcar como encontrado", marcar_como_encontrado_perros_perdido_path(perros), method: :patch, class: "btn btn-turqueza", style: 'margin: 2px;' %>
            </div>
          
          <% end %>


        <% end %>
      </div>
    </div>


  <% end %>

</div>

<%= render "perros_perdidos/pagination" %>

<script>
  document.addEventListener('turbo:load', function() {
    function toggleElements(showMisPerros) {
      var misPerrosDiv = document.querySelector('.mis_perros');
      var noMisPerrosDiv = document.querySelector('.no_mis_perros');

      if (showMisPerros) {
        misPerrosDiv.style.display = 'block';
        noMisPerrosDiv.style.display = 'none';
      } else {
        misPerrosDiv.style.display = 'none';
        noMisPerrosDiv.style.display = 'block';
      }
    }

    function loadState() {
      var showMisPerros = window.location.pathname.includes('/se-busca') && window.location.search.includes('filter');
      toggleElements(showMisPerros);

      var noMisPerrosDiv = document.querySelector('.no_mis_perros');
      var misPerrosDiv = document.querySelector('.mis_perros');
      
      // Si la URL contiene solo /se-busca
      if (window.location.pathname === '/se-busca' && !window.location.search.includes('filter')) {
        noMisPerrosDiv.style.display = 'block';
        misPerrosDiv.style.display = 'none';
      }
    }

    loadState();

    var perrosEncontradosBoton = document.querySelector('.perros-encontrados-boton');
    if (perrosEncontradosBoton) {
      perrosEncontradosBoton.addEventListener('click', function() {
        toggleElements(false);
      });
    }

    var misPerrosEncontradosBoton = document.querySelector('.mis-perros-encontrados-boton');
    if (misPerrosEncontradosBoton) {
      misPerrosEncontradosBoton.addEventListener('click', function() {
        toggleElements(true);
      });
    }
  });
</script>

app/views/perros_perdidos/new.html.erb
<h1>Publicar un perro perdido.</h1>


<%= render "form", perros_perdido: @perros_perdido %>

app/views/perros_perdidos/show.html.erb
<%= render @perros_perdido %>

<div>
  <%= link_to "Editar", edit_perros_perdido_path(@perros_perdido) %> |
  <%= link_to "Volver", perros_perdidos_path %>

  <%= button_to "Eliminar", @perros_perdido, method: :delete %>
</div>