config/routes.rb
Rails.application.routes.draw do
  # Configurar  MercadoPago
  post 'mercadopago_checkout', to: 'campania_donacions#realizar_pago'
  post 'webhooks', to: 'campania_donacions#actualizar_donacion'

  resources :campania_donacions
  resources :campania

  resources :vet_de_guardia
  resources :historia_clinicas
  resources :ambulatoria
  resources :desparasitacions
  resources :vacuna_rs
  resources :vacuna_es
  resources :castracions
  resources :historia_cs
  resources :perros_que_buscan_parejas

  resources :perros_en_adopcions

  resources :turnos
  get  'turnos', to: 'turnos#index'
  post 'turnos/generar', to: 'turnos#generar', as: 'generar_turno'
  post 'turnos/rechazar', to: 'turnos#rechazar', as: 'rechazar_turno'
  post 'turnos/cancelar-v', to: 'turnos#cancelar_veterinario', as: 'cancelar_turno_veterinario'
  post 'turnos/cancelar-c', to: 'turnos#cancelar_cliente', as: 'cancelar_turno_cliente'
  delete 'turnos', to: 'turnos#destroy'

  root 'home#index'

  devise_for :users, path_prefix: 'my', controllers: {
    registrations: 'users/registrations'
  }
 # devise_for :users,: :path_prefix => 'my'
  resources :users, only: [:index, :atencion]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'perfil', to: 'users#ver_perfil'
    get 'edit_user', to: 'users/registrations#edit'
    patch 'update_user_registration', to: 'users/registrations#update'
  end
  resources :users do
    collection do
      get 'atencion'
    end
  resources :users do
    member do
      get 'agregar_perrito'
      post 'crear_perrito'
    end
  end
  resources :users do
    resources :perritos # Esto anida las rutas de perritos dentro de las rutas de usuarios
  end


  get 'profile/edit', to: 'profile#edit', as: :edit_profile
  end

  #Creacion de usuario del veterinario
  get 'creacion_usuario', to: 'users/registro#new', as: 'creacion_usuario'
  post 'creacion_usuario', to: 'users/registro#create'

  #Atencion al cliente
  get 'perrito_ajeno/:id', to: 'perritos#new_ajeno', as: 'perrito_ajeno'
  get 'edit_other/:id', to: 'users#edit_otro', as: 'edit_other'
  get 'usuarios/:id', to: 'users#ver_perfil'
  get '/perfil/:id', to: 'users#ver_perfil', as: 'ver_perfil'
  get 'atencion_cliente', to: 'users#atencion'

  #Interfaz de los perros
  get 'show_perrito/:id', to: 'perritos#show', as: 'show_perrito'
  get 'add_dog.:id', to: 'perritos#new', as: 'add_dog'
  get 'marcar_fallecido/:id', to: 'perritos#marcar_fallecido', as: 'marcar_fallecido'
  resources :perritos do
    member do
      patch 'marcar_fallecido'
    end
  end
  #Historia clinica del perro
  get 'ver_perrito/:id', to: 'perritos#ver', as: 'ver_perrito'
  get 'ver_perrito_ajeno/:id', to: 'perritos#ver_ajeno', as: 'ver_perrito_ajeno'
  get 'crear_historia/:id', to: 'perritos#agregar_historia', as: 'crear_historia'
  get 'crear_castracion/:id', to: 'historia_clinicas#new_castracion', as: 'crear_castracion'
  get 'crear_vacunae/:id', to: 'historia_clinicas#new_vacunae', as: 'crear_vacunae'
  get 'crear_vacunar/:id', to: 'historia_clinicas#new_vacunar', as: 'crear_vacunar'
  get 'crear_desparasitacion/:id', to: 'historia_clinicas#new_desparasitacion', as: 'crear_desparasitacion'
  get 'crear_atencion_clinica/:id', to: 'historia_clinicas#new_atencion_clinica', as: 'crear_atencion_clinica'
  get 'ver_castracion/:id', to: 'historia_clinicas#ver_castracion', as: 'ver_castracion'
  get 'ver_desparasitacion/:id', to: 'historia_clinicas#ver_desparasitacion', as: 'ver_desparasitacion'
  get 'ver_vacunar/:id', to: 'historia_clinicas#ver_vacunar', as: 'ver_vacunar'
  get 'ver_vacunae/:id', to: 'historia_clinicas#ver_vacunae', as: 'ver_vacunae'
  get 'ver_atencion/:id', to: 'historia_clinicas#ver_atencion', as: 'ver_atencion'
  resources :historia_clinicas do
    post 'create_vacunar', on: :collection
    post 'create_vacunae', on: :collection
  end

  #Envio de mail de joaco
  post '/random_password_email', to: 'user_mailer#random_password_email'

  #Campañas de donacion
  get 'ver_campanias', to: 'campania_donacions#index', as: 'ver_campanias'
  get 'cargar_campania', to: 'campania_donacions#cargar', as: 'cargar_campania'
  get 'eliminar_campania', to: 'campania_donacions#destroy', as: 'eliminar_campania'
  get 'editar_campania/:id', to: 'campania_donacions#editar', as: 'editar_campania'
  resources :campanias do
    post 'crear_campania', on: :collection
    resources :campania_donacions, only: [:destroy]
  end


  resources :cuidador_paseadors, path: 'cuidadores-y-paseadores'
  resources :perros_perdidos, path: 'se-busca'

  resources :perros_encontrados do
    collection do
      get 'edit_no_registrado'
    end
  end

  resources :perros_encontrados
  resources :perritos

  patch '/perros_perdidos/:id/marcar_como_encontrado', to: 'perros_perdidos#marcar_como_encontrado', as: :marcar_como_encontrado_perros_perdido
  patch '/perros_encontrados/:id/marcar_como_dueno_encontrado', to: 'perros_encontrados#marcar_como_dueno_encontrado', as: :marcar_como_dueno_encontrado_perros_encontrado
  patch '/perros_en_adopcion/:id/marcar_como_adoptado', to: 'perros_en_adopcions#marcar_como_adoptado', as: :marcar_como_adoptado_perros_en_adopcion

  #mails javi
  post '/enviar_correo', to: 'cuidador_paseadors#enviar_correo'
  post '/enviar_correo_no_registrado', to: 'cuidador_paseadors#enviar_correo_no_registrado'

  post '/enviar_correo_perros_perdidos', to: 'perros_perdidos#enviar_correo_perros_perdidos'
  post '/enviar_correo_perros_encontrados', to: 'perros_encontrados#enviar_correo_perros_encontrados'
  post '/enviar_correo_perros_encontrados_no_registrado', to: 'perros_encontrados#enviar_correo_perros_encontrados_no_registrado'

  resources :perros_encontrados do
    member do
      post 'enviar_correo_perros_encontrados_no_registrado'
    end
  end

 # config/routes.rb
get '/perros_encontrados/edit_no_registrado', to: 'perros_encontrados#edit_no_registrado', as: 'edit_no_registrado_perros_encontrado'








  post '/enviar_correo_perros_perdidos_contactar', to: 'perros_perdidos#enviar_correo_perros_perdidos_contactar'
  post '/enviar_correo_perros_encontrados_contactar', to: 'perros_encontrados#enviar_correo_perros_encontrados_contactar'
  post '/enviar_correo_contactar_registrado', to: 'perros_en_adopcions#enviar_correo_contactar_registrado'
  post '/enviar_correo_contactar_no_registrado', to: 'perros_en_adopcions#enviar_correo_contactar_no_registrado'

  resources :perros_que_buscan_parejas do
    post 'postular', on: :member
    post 'retirar', on: :member
    get 'buscar_pareja', on: :member
    post 'me_gusta', on: :member
    post 'no_me_gusta', on: :member
    post 'ya_no_me_gusta', on: :member
    get 'ver_mis_no_me_gusta', on: :member
    post 'retirar_no_me_gusta', on: :member
    get 'ver_perros_que_me_dieron_me_gusta', on: :member
    get 'ver_los_matcheos_de_mi_perro', on: :member
  end


end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def create
    super do |resource|
      if resource.persisted?
        # Si el usuario se ha creado con éxito, crea un perrito asociado
        perrito_attributes = params.require(:user).permit(perrito: {}).permit!
        puts perrito_attributes
        resource.perritos.create(perrito_attributes[:perrito])
      end
    end
  end

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nombre, :apellido, :email, :password, :password_confirmation, :tipo_usuario, :perrito_attributes => [:nombre_perro, :fecha_de_nacimiento, :caracteristicas, :condiciones, :raza, :color, :tamaño]])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :apellido, :email, :password, :password_confirmation, perrito_attributes: [:nombre_perro, :dia, :mes, :año, :caracteristicas, :condiciones, :raza, :color, :tamaño]])
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :apellido, :email, :password, :password_confirmation, :direccion, :nro, :tipo_usuario, :perrito_attributes => [:nombre_perro, :dia, :mes, :año, :caracteristicas, :condiciones, :raza, :color, :tamaño]])
  end




  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
   #  devise_parameter_sanitizer.permit(:account_update, keys: [:nombre, :apellido])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :apellido, :email, :password, :password_confirmation, :perrito_attributes => [:nombre_perro, :dia, :mes, :año, :caracteristicas, :condiciones, :raza, :color, :tamaño]])
   end

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :apellido, :email, :password, :password_confirmation, perrito_attributes: [:nombre_perro, :dia, :mes, :año, :caracteristicas, :condiciones, :raza, :color, :tamaño]])
  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registro_controller.rb
class Users::RegistroController < ApplicationController
    before_action :authenticate_user!

    def new
      @user = User.new
    end

    def create
      user_params_without_perrito = user_params.except(:perrito)
      @user = User.create(user_params_without_perrito)
      random_password = SecureRandom.base64(8)
      while(!(random_password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/)))
        random_password = SecureRandom.base64(8)
      end
      @user.password = random_password
      @user.password_confirmation = random_password
      if @user.save
        UserMailer.random_password_email(@user.email, random_password).deliver_later
        @user.perritos.create(user_params[:perrito])
        redirect_to atencion_cliente_path
        flash[:notice] = 'Creación de usuario exitosa'
      else
        flash[:alert] = "Fallo la creacion de usuario"
        redirect_to creacion_usuario_path
      end
    end

    private

    def user_params
      params.require(:user).permit(:nombre, :apellido, :email, :direccion, :nro, :telefono, :tipo_usuario, :perrito => [:nombre, :dia, :mes, :año, :caracteristicas, :condiciones, :raza, :sexo, :color, :tamaño, :fallecido]) # Tus atributos de User
    end
  end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/atencion.html.erb
<% if current_user.tipo_usuario == 'veterinario' %>

<style>
/* Estilos para la tabla */
#datos {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
    background-color: #f7f7f7;
    border: 1px solid #ddd;
}

#datos th, #datos td {
    padding: 10px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

#datos th {
    background-color: #0D9BB5;
    color: #fff;
}

#datos tr:nth-child(even) {
    background: #f2f2f2;
}

/* Estilos para la entrada de búsqueda */
#searchTerm {
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 4px;
}

/* Estilos para las celdas resaltadas en la búsqueda */
.matched {
    background-color: #ffcc99;
    font-weight: bold;
    color: #333;
}
</style>



<div class="d-flex align-items-center justify-content-between">
  <%= link_to "Crear usuario", creacion_usuario_path, class: "btn btn-turqueza" %>
  <form style="margin: 20px;">
  Buscar: <input id="searchTerm" type="text" onkeyup="doSearch()" />
</form>
</div>


<script>
  function doSearch() {
    var tableReg = document.getElementById('datos');
    var searchInput = document.getElementById('searchTerm').value.toLowerCase();
    var cellsOfRow = "";
    var encontro = 0;

    for (var i = 1; i < tableReg.rows.length; i++) {
      cellsOfRow = tableReg.rows[i].getElementsByTagName('td');
      var found = false;

      var nameAndLastName = (cellsOfRow[0].innerHTML + ' ' + cellsOfRow[1].innerHTML).toLowerCase();

      if (nameAndLastName.indexOf(searchInput) > -1) {
        found = true;
      }

      if (found) {
        tableReg.rows[i].style.display = '';
        encontro++;
      } else {
        tableReg.rows[i].style.display = 'none';
      }
    }
    var mensajeElement = document.getElementById("mensaje-no-encontrado");
    if (mensajeElement) {
      mensajeElement.innerHTML = encontro === 0 ? 'No se encontró ninguna persona con ese nombre y/o apellido.' : '';
    }
  }
</script>


<% if @users.any? %>
  <table id="datos">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Email</th>
        <th>Tipo</th>
        <th>Acciones</th>
        <!-- Agrega más columnas según tus necesidades -->
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% unless (user.id==current_user.id) %>
        <tr>
          <td><%= user.nombre %></td>
          <td><%= user.apellido %></td>
          <td><%= user.email %></td>
          <td><%= user.tipo_usuario %></td>
          <td>
            <a href="<%= user_path(user) %>"  style="text-decoration: none; color: #0D9BB5; transition: color 0.1s;" onmouseover="this.style.color='#FF914C'" onmouseout="this.style.color='#0D9BB5'">Ver perfil</a>
          </td>
          <!-- Agrega más celdas según tus necesidades -->
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <p id="mensaje-no-encontrado"></p>
<% else %>
  <p>No hay clientes registrados.</p>
<% end %>
<% end %>

app/views/users/ver_perfil.html.erb
<div class="container mt-5">
  <h2 style="margin-block: 20px;">Cuenta</h2>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Nombre</th>
        <td><%= current_user.nombre %></td>
      </tr>
      <tr>
        <th>Apellido</th>
        <td><%= current_user.apellido %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= current_user.email %></td>
      </tr>
      <tr>
        <th>Dirección</th>
        <td><%= current_user.direccion %></td>
      </tr>
      <tr>
        <th>Número</th>
        <td><%= current_user.nro %></td>
      </tr>
      <tr>
        <th>Telefono</th>
        <td><%= current_user.telefono %></td>
      </tr>
      <tr>
        <th>Tipo de Usuario</th>
        <td><%= current_user.tipo_usuario %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to "Editar Perfil", edit_user_path(current_user), class: "btn btn-secondary" %>
</div>

<div style="margin: 20px;">
  <h2> Tus perros </h2>

<div class='d-flex'>
  <label class="form-check-label" style='margin: 5px; margin-right: 7px;'>  </label>
  <div class="form-check", style='margin: 5px;'>
    <input class="form-check-input" type="checkbox" value="" id="fallecidos-check">
    <label class="form-check-label" for="flexCheckChecked">
      Mostrar perros fallecidos
    </label>
  </div>
</div>


<% if current_user.perritos.empty? %>
  <p class="text-muted">No cuentas con perros actualmente, ¡Visita la sección de perros en adopción y encontra el compañero que estas buscando!.</p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nombre del perro</th>
        <th>Raza</th>
        <th>Fecha de Nacimiento</th>
        <th>Acciones</th>
      </tr>
    </thead>

    

    <tbody>
    <% current_user.perritos.each do |perrito| %>
      <tr class="<%= (perrito.fallecido) ? 'filasfallecidos' : '' %>" data-rol="<%= perrito.fallecido %>">
          <td><%= perrito.nombre %></td>
          <td><%= perrito.raza %></td>
          <td><%= "#{perrito.dia}/#{perrito.mes}/#{perrito.año}" %></td>
          <td>
            <!-- Botón "Editar" y "Eliminar" para el veterinario -->
            <% if current_user.tipo_usuario == 'veterinario' %>
              <%= link_to "Editar", edit_perrito_path(perrito, tipo: 'mio'), class: "btn btn-sm btn-secondary" %>
              <%# link_to "Eliminar", perrito, data: { turbo_method: :delete }, class: "btn btn-sm btn-danger" %>
            <% end %>
            <%= link_to "Ver perro", ver_perrito_path(perrito, user: current_user), class: "btn btn-sm btn-secondary" %>
            <% if perrito.fallecido == false %>
              <%= link_to "Marcar como fallecido", marcar_fallecido_path(perrito, tipo: 'mio', user: current_user), class: "btn btn-sm btn-secondary" %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
  </table>
<% end %>

<% if @perritos_vivos.empty? %>
  <p id="mensaje-perros" class="text-muted">
    No cuentas con perros actualmente. ¡Visita la sección de perros en adopción y encuentra el compañero que estás buscando!
  </p>
<% end %>

        <% if current_user.tipo_usuario == 'veterinario' %>
             <%= link_to "Agregar perro", add_dog_path(current_user, tipo: 'mio'), class: "btn btn-turqueza" %>
        <% end %>


</div>

<script>
  document.addEventListener("turbo:load", function() {

    // Obtiene referencias a los checkboxes y a los elementos de la lista
    const fallecidosCheckbox = document.getElementById("fallecidos-check");
    const listItems = document.querySelectorAll(".filasfallecidos");
    
    for (var i = 0; i < listItems.length; i++) {
      listItems[i].style.display = 'none';
    }

    // Agrega event listeners a los checkboxes

    fallecidosCheckbox.addEventListener("change", actualizarLista);

    // Función para actualizar la visibilidad de los elementos de la lista
    function actualizarLista() {
      const mostrarFallecidos = fallecidosCheckbox.checked;

      listItems.forEach(function(item) {
        const muerto = item.getAttribute("data-rol");

          if ((!mostrarFallecidos) &&  (muerto)// Checkbox de mostrar fallecidos marcado y el perro esta muerto
        ) {
            item.style.display = "none"; // Ocultar el elemento
        } else {
          item.style.display = ""; // Mostrar el elemento sin modificar su formato
        }
      });
    }
  });
</script>

<script>
  document.addEventListener("turbo:load", function() {
    const fallecidosCheckbox = document.getElementById("fallecidos-check");
    const mensajePerros = document.getElementById("mensaje-perros");

    if ( <%= !@perritos_vivos.empty? %>) {
        mensajePerros.style.display = 'none';
      } else {
        mensajePerros.style.display = 'block';
      }

    fallecidosCheckbox.addEventListener("change", function() {
      const mostrarFallecidos = fallecidosCheckbox.checked;

      if !(!mostrarFallecidos && <%= @perritos_vivos.empty? %>) {
        mensajePerros.style.display = 'none';
      } else {
        mensajePerros.style.display = 'block';
      }
    });
  });
</script>