config/routes.rb
Rails.application.routes.draw do
  # Configurar  MercadoPago
  post 'mercadopago_checkout', to: 'campania_donacions#realizar_pago'
  post 'webhooks', to: 'campania_donacions#actualizar_donacion'

  resources :campania_donacions
  resources :campania

  resources :vet_de_guardia
  resources :historia_clinicas
  resources :ambulatoria
  resources :desparasitacions
  resources :vacuna_rs
  resources :vacuna_es
  resources :castracions
  resources :historia_cs
  resources :perros_que_buscan_parejas

  resources :perros_en_adopcions

  resources :turnos
  get  'turnos', to: 'turnos#index'
  post 'turnos/generar', to: 'turnos#generar', as: 'generar_turno'
  post 'turnos/rechazar', to: 'turnos#rechazar', as: 'rechazar_turno'
  post 'turnos/cancelar-v', to: 'turnos#cancelar_veterinario', as: 'cancelar_turno_veterinario'
  post 'turnos/cancelar-c', to: 'turnos#cancelar_cliente', as: 'cancelar_turno_cliente'
  delete 'turnos', to: 'turnos#destroy'

  root 'home#index'

  devise_for :users, path_prefix: 'my', controllers: {
    registrations: 'users/registrations'
  }
 # devise_for :users,: :path_prefix => 'my'
  resources :users, only: [:index, :atencion]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
    get 'perfil', to: 'users#ver_perfil'
    get 'edit_user', to: 'users/registrations#edit'
    patch 'update_user_registration', to: 'users/registrations#update'
  end
  resources :users do
    collection do
      get 'atencion'
    end
  resources :users do
    member do
      get 'agregar_perrito'
      post 'crear_perrito'
    end
  end
  resources :users do
    resources :perritos # Esto anida las rutas de perritos dentro de las rutas de usuarios
  end


  get 'profile/edit', to: 'profile#edit', as: :edit_profile
  end

  #Creacion de usuario del veterinario
  get 'creacion_usuario', to: 'users/registro#new', as: 'creacion_usuario'
  post 'creacion_usuario', to: 'users/registro#create'

  #Atencion al cliente
  get 'perrito_ajeno/:id', to: 'perritos#new_ajeno', as: 'perrito_ajeno'
  get 'edit_other/:id', to: 'users#edit_otro', as: 'edit_other'
  get 'usuarios/:id', to: 'users#ver_perfil'
  get '/perfil/:id', to: 'users#ver_perfil', as: 'ver_perfil'
  get 'atencion_cliente', to: 'users#atencion'

  #Interfaz de los perros
  get 'show_perrito/:id', to: 'perritos#show', as: 'show_perrito'
  get 'add_dog.:id', to: 'perritos#new', as: 'add_dog'
  get 'marcar_fallecido/:id', to: 'perritos#marcar_fallecido', as: 'marcar_fallecido'
  resources :perritos do
    member do
      patch 'marcar_fallecido'
    end
  end
  #Historia clinica del perro
  get 'ver_perrito/:id', to: 'perritos#ver', as: 'ver_perrito'
  get 'ver_perrito_ajeno/:id', to: 'perritos#ver_ajeno', as: 'ver_perrito_ajeno'
  get 'crear_historia/:id', to: 'perritos#agregar_historia', as: 'crear_historia'
  get 'crear_castracion/:id', to: 'historia_clinicas#new_castracion', as: 'crear_castracion'
  get 'crear_vacunae/:id', to: 'historia_clinicas#new_vacunae', as: 'crear_vacunae'
  get 'crear_vacunar/:id', to: 'historia_clinicas#new_vacunar', as: 'crear_vacunar'
  get 'crear_desparasitacion/:id', to: 'historia_clinicas#new_desparasitacion', as: 'crear_desparasitacion'
  get 'crear_atencion_clinica/:id', to: 'historia_clinicas#new_atencion_clinica', as: 'crear_atencion_clinica'
  get 'ver_castracion/:id', to: 'historia_clinicas#ver_castracion', as: 'ver_castracion'
  get 'ver_desparasitacion/:id', to: 'historia_clinicas#ver_desparasitacion', as: 'ver_desparasitacion'
  get 'ver_vacunar/:id', to: 'historia_clinicas#ver_vacunar', as: 'ver_vacunar'
  get 'ver_vacunae/:id', to: 'historia_clinicas#ver_vacunae', as: 'ver_vacunae'
  get 'ver_atencion/:id', to: 'historia_clinicas#ver_atencion', as: 'ver_atencion'
  resources :historia_clinicas do
    post 'create_vacunar', on: :collection
    post 'create_vacunae', on: :collection
  end

  #Envio de mail de joaco
  post '/random_password_email', to: 'user_mailer#random_password_email'

  #Campañas de donacion
  get 'ver_campanias', to: 'campania_donacions#index', as: 'ver_campanias'
  get 'cargar_campania', to: 'campania_donacions#cargar', as: 'cargar_campania'
  get 'eliminar_campania', to: 'campania_donacions#destroy', as: 'eliminar_campania'
  get 'editar_campania/:id', to: 'campania_donacions#editar', as: 'editar_campania'
  resources :campanias do
    post 'crear_campania', on: :collection
    resources :campania_donacions, only: [:destroy]
  end


  resources :cuidador_paseadors, path: 'cuidadores-y-paseadores'
  resources :perros_perdidos, path: 'se-busca'

  resources :perros_encontrados do
    collection do
      get 'edit_no_registrado'
    end
  end

  resources :perros_encontrados
  resources :perritos

  patch '/perros_perdidos/:id/marcar_como_encontrado', to: 'perros_perdidos#marcar_como_encontrado', as: :marcar_como_encontrado_perros_perdido
  patch '/perros_encontrados/:id/marcar_como_dueno_encontrado', to: 'perros_encontrados#marcar_como_dueno_encontrado', as: :marcar_como_dueno_encontrado_perros_encontrado
  patch '/perros_en_adopcion/:id/marcar_como_adoptado', to: 'perros_en_adopcions#marcar_como_adoptado', as: :marcar_como_adoptado_perros_en_adopcion

  #mails javi
  post '/enviar_correo', to: 'cuidador_paseadors#enviar_correo'
  post '/enviar_correo_no_registrado', to: 'cuidador_paseadors#enviar_correo_no_registrado'

  post '/enviar_correo_perros_perdidos', to: 'perros_perdidos#enviar_correo_perros_perdidos'
  post '/enviar_correo_perros_encontrados', to: 'perros_encontrados#enviar_correo_perros_encontrados'
  post '/enviar_correo_perros_encontrados_no_registrado', to: 'perros_encontrados#enviar_correo_perros_encontrados_no_registrado'

  resources :perros_encontrados do
    member do
      post 'enviar_correo_perros_encontrados_no_registrado'
    end
  end

 # config/routes.rb
get '/perros_encontrados/edit_no_registrado', to: 'perros_encontrados#edit_no_registrado', as: 'edit_no_registrado_perros_encontrado'








  post '/enviar_correo_perros_perdidos_contactar', to: 'perros_perdidos#enviar_correo_perros_perdidos_contactar'
  post '/enviar_correo_perros_encontrados_contactar', to: 'perros_encontrados#enviar_correo_perros_encontrados_contactar'
  post '/enviar_correo_contactar_registrado', to: 'perros_en_adopcions#enviar_correo_contactar_registrado'
  post '/enviar_correo_contactar_no_registrado', to: 'perros_en_adopcions#enviar_correo_contactar_no_registrado'

  resources :perros_que_buscan_parejas do
    post 'postular', on: :member
    post 'retirar', on: :member
    get 'buscar_pareja', on: :member
    post 'me_gusta', on: :member
    post 'no_me_gusta', on: :member
    post 'ya_no_me_gusta', on: :member
    get 'ver_mis_no_me_gusta', on: :member
    post 'retirar_no_me_gusta', on: :member
    get 'ver_perros_que_me_dieron_me_gusta', on: :member
    get 'ver_los_matcheos_de_mi_perro', on: :member
  end


end

app/models/historia_clinica.rb
class HistoriaClinica < ApplicationRecord
  belongs_to :perrito
end

app/controllers/historia_clinicas_controller.rb
class HistoriaClinicasController < ApplicationController
  before_action :set_historia_clinica, only: %i[ show edit update destroy ]

  # GET /historia_clinicas or /historia_clinicas.json
  def index
    @historia_clinicas = HistoriaClinica.all
  end

  # GET /historia_clinicas/1 or /historia_clinicas/1.json
  def show
  end

  # GET /historia_clinicas/new
  def new
    @historia_clinica = HistoriaClinica.new
  end

  def new_castracion
    @historia_clinica = HistoriaClinica.new
    @perrito = Perrito.find(params[:id])
    @tipo = params[:tipo]
    @user = User.find(params[:user_id])
  end

  def new_desparasitacion
    @historia_clinica = HistoriaClinica.new
    @perrito = Perrito.find(params[:id])
    @tipo = params[:tipo]
    @user = User.find(params[:user_id])
    puts '########################'
    puts 'USER ID NEW DESPARASITACION'
    puts @user.id
  end

  def new_atencion_clinica
    @historia_clinica = HistoriaClinica.new
    @perrito = Perrito.find(params[:id])
    @tipo = params[:tipo]
    @user = User.find(params[:user_id])
  end

  def new_vacunae
    @historia_clinica = HistoriaClinica.new
    @perrito = Perrito.find(params[:id])
    @tipo = params[:tipo]
    @user = User.find(params[:user_id])
  end

  def new_vacunar
    @historia_clinica = HistoriaClinica.new
    @perrito = Perrito.find(params[:id])
    @tipo = params[:tipo]
    @user = User.find(params[:user_id])
  end

  # GET /historia_clinicas/1/edit
  def edit
  end

  # POST /historia_clinicas or /historia_clinicas.json
  def create
    puts '###################################'
    puts 'ENTRE A CREATE SOLO'
    puts 'VALOR DE quien'
    @quien = params[:historia_clinica][:quien]
    puts @quien
    if (@quien == 'ajeno')
      @user = User.find(params[:historia_clinica][:user_id])
    else
      @user = current_user
    end
    puts '####################################'
    puts 'USER ID EN CREATE'
    puts @user.id
    perrito_id = params[:historia_clinica][:id]
    @perrito = Perrito.find(perrito_id)
    parametros = historia_clinica_params.except(:id, :quien, :user_id, :fecha)
    @historia_clinica = @perrito.historia_clinicas.build(parametros)
    @fecha = Date.parse(params[:historia_clinica][:fecha])
    @historia_clinica.dia = @fecha.day
    @historia_clinica.mes = @fecha.month
    @historia_clinica.año = @fecha.year
    respond_to do |format|
      if @historia_clinica.save
        if (@quien == 'ajeno')
          format.html { redirect_to ver_perrito_ajeno_path(@perrito, user_id: @user.id), notice: 'Se registró la historia clínica con éxito.' }
        else
          format.html { redirect_to ver_perrito_path(@perrito, user: current_user), notice: 'Se registró la historia clínica con éxito.' }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @historia_clinica.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_vacunae
    puts '###################################'
    puts 'ENTRE A CREATE_VACUNAE'
    puts 'VALOR DE quien'
    @quien = params[:historia_clinica][:quien]
    puts @quien
    if (@quien == 'ajeno')
      @user = User.find(params[:historia_clinica][:user_id])
    else
      @user = current_user
    end
    @fecha = Date.parse(params[:historia_clinica][:fecha])
    @dia = @fecha.day
    @mes = @fecha.month
    @año = @fecha.year
    perrito_id = params[:historia_clinica][:id]
    @perrito = Perrito.find(perrito_id)
    @historias = @perrito.historia_clinicas
    fecha_perrito = Date.new(@perrito.año, @perrito.mes, @perrito.dia)
    fecha_historia_clinica = Date.new(@año.to_i, @mes.to_i, @dia.to_i)
    if((fecha_historia_clinica - fecha_perrito).to_i > 4*30)
      vacunase_validas?(params[:historia_clinica])
      if (@puede)
        parametros = historia_clinica_params.except(:id, :quien, :user_id, :fecha)
        @historia_clinica = @perrito.historia_clinicas.build(parametros)
        @fecha = Date.parse(params[:historia_clinica][:fecha])
        @historia_clinica.dia = @fecha.day
        @historia_clinica.mes = @fecha.month
        @historia_clinica.año = @fecha.year
    
        respond_to do |format|
          if @historia_clinica.save
            if (@quien == 'ajeno')
              format.html { redirect_to ver_perrito_ajeno_path(@perrito, user_id: @user.id), notice: 'Se registró la historia clínica con éxito.' }
            else
              format.html { redirect_to ver_perrito_path(@perrito, user: current_user), notice: 'Se registró la historia clínica con éxito.' }
            end
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @historia_clinica.errors, status: :unprocessable_entity }
          end
        end
      else
        flash[:alert] = 'Fallo la carga de la vacunación: el perro se vacuno hace menos de 1 año'
        redirect_to ver_perrito_path(@perrito, @user)
      end
    else
      flash[:alert] = 'Fallo la carga de la vacunación: el perro tiene menos de 4 meses'
      redirect_to ver_perrito_path(@perrito, @user)
    end
  end

  def create_vacunar
    puts '###################################'
    puts 'ENTRE A CREATE_VACUNAR'
    @quien = params[:historia_clinica][:quien]
    if (@quien == 'ajeno')
      @user = User.find(params[:historia_clinica][:user_id])
    else
      @user = current_user
    end
    @fecha = Date.parse(params[:historia_clinica][:fecha])
    @dia = @fecha.day
    @mes = @fecha.month
    @año = @fecha.year
    perrito_id = params[:historia_clinica][:id]
    @perrito = Perrito.find(perrito_id)
    @historias = @perrito.historia_clinicas
    fecha_perrito = Date.new(@perrito.año, @perrito.mes, @perrito.dia)
    fecha_historia_clinica = Date.new(@año.to_i, @mes.to_i, @dia.to_i)
    #CASO ENTRE 2 Y 4 MESES (FALTA CHECKEAR SI SE DIO UNA VACUNA 21 DIAS ANTES)
    if ((fecha_historia_clinica - fecha_perrito).to_i > 2 * 30 && (fecha_historia_clinica - fecha_perrito).to_i < 4 * 30)
      #Checkeo si se dio una vacuna hace menos de 21 dias
      puts '#####################################'
      puts 'ENTRE AL IF DE ENTRE 2 Y 4 MESES'
      vacunasr_validas_2_a_4_meses?(params[:historia_clinica])
      if (@puede)
        parametros = historia_clinica_params.except(:id, :quien, :user_id, :fecha)
        @historia_clinica = @perrito.historia_clinicas.build(parametros)
        @fecha = Date.parse(params[:historia_clinica][:fecha])
        @historia_clinica.dia = @fecha.day
        @historia_clinica.mes = @fecha.month
        @historia_clinica.año = @fecha.year
    
        respond_to do |format|
          if @historia_clinica.save
            if (@quien == 'ajeno')
              format.html { redirect_to ver_perrito_ajeno_path(@perrito, user_id: @user.id), notice: 'Se registró la historia clínica con éxito.' }
            else
              format.html { redirect_to ver_perrito_path(@perrito, user: current_user), notice: 'Se registró la historia clínica con éxito.' }
            end
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @historia_clinica.errors, status: :unprocessable_entity }
          end
        end
      else
        flash[:alert] = 'Fallo la carga de la vacunación: el perro se vacunó hace menos de 21 dias'
        redirect_to ver_perrito_path(@perrito, @user)
      end
    else
      #CASO MAYOR A 4 MESES (FALTA CHECKEAR SI SE DIO UNA VACUNA UN AÑO ANTES)
      if((fecha_historia_clinica - fecha_perrito).to_i > 4 * 30)
        #Checkeo si se dio una vacuna hace menos de 1 año
        puts '#################################################'
        puts 'ENTRE AL IF MAYOR A 4 MESES'
        vacunas_validas?(params[:historia_clinica])
        if (@puede)
          parametros = historia_clinica_params.except(:id, :quien, :user_id, :fecha)
          @historia_clinica = @perrito.historia_clinicas.build(parametros)
          @fecha = Date.parse(params[:historia_clinica][:fecha])
          @historia_clinica.dia = @fecha.day
          @historia_clinica.mes = @fecha.month
          @historia_clinica.año = @fecha.year
      
          respond_to do |format|
            if @historia_clinica.save
              if (@quien == 'ajeno')
                format.html { redirect_to ver_perrito_ajeno_path(@perrito, user_id: @user.id), notice: 'Se registró la historia clínica con éxito.' }
              else
                format.html { redirect_to ver_perrito_path(@perrito, user: current_user), notice: 'Se registró la historia clínica con éxito.' }
              end
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @historia_clinica.errors, status: :unprocessable_entity }
            end
          end
        else
          flash[:alert] = 'Fallo la carga de la vacunación: el perro se vacunó hace menos de 1 año'
          redirect_to ver_perrito_path(@perrito, @user)
        end
      else
        flash[:alert] = 'Fallo la carga de la vacunación: el perro posee menos de 2 meses de vida'
        redirect_to ver_perrito_path(@perrito, @user)
      end

    end
  end

  # PATCH/PUT /historia_clinicas/1 or /historia_clinicas/1.json
  def update
    respond_to do |format|
      if @historia_clinica.update(historia_clinica_params)
        format.html { redirect_to historia_clinica_url(@historia_clinica), notice: "Historia clinica was successfully updated." }
        format.json { render :show, status: :ok, location: @historia_clinica }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @historia_clinica.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /historia_clinicas/1 or /historia_clinicas/1.json
  def destroy
    @historia_clinica.destroy!

    respond_to do |format|

app/helpers/historia_clinicas_helper.rb
module HistoriaClinicasHelper
end

app/views/historia_clinicas/_historia_clinica.html.erb
<div id="<%= dom_id historia_clinica %>">
  <p>
    <strong>Perrito:</strong>
    <%= historia_clinica.perrito_id %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= historia_clinica.tipo %>
  </p>

  <p>
    <strong>Dia:</strong>
    <%= historia_clinica.dia %>
  </p>

  <p>
    <strong>Mes:</strong>
    <%= historia_clinica.mes %>
  </p>

  <p>
    <strong>Año:</strong>
    <%= historia_clinica.año %>
  </p>

  <p>
    <strong>Detalle:</strong>
    <%= historia_clinica.detalle %>
  </p>

  <p>
    <strong>Tipovacuna:</strong>
    <%= historia_clinica.tipoVacuna %>
  </p>

  <p>
    <strong>Lote:</strong>
    <%= historia_clinica.lote %>
  </p>

  <p>
    <strong>Dosis:</strong>
    <%= historia_clinica.dosis %>
  </p>

  <p>
    <strong>Producto:</strong>
    <%= historia_clinica.producto %>
  </p>

  <p>
    <strong>Sintomas:</strong>
    <%= historia_clinica.sintomas %>
  </p>

  <p>
    <strong>Diagnostico:</strong>
    <%= historia_clinica.diagnostico %>
  </p>

  <p>
    <strong>Tratamiento:</strong>
    <%= historia_clinica.tratamiento %>
  </p>

</div>

app/views/historia_clinicas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Historia clinicas</h1>

<div id="historia_clinicas">
  <% @historia_clinicas.each do |historia_clinica| %>
    <%= render historia_clinica %>
    <p>
      <%= link_to "Show this historia clinica", historia_clinica %>
    </p>
  <% end %>
</div>

<%= link_to "New historia clinica", new_historia_clinica_path %>

app/views/historia_clinicas/new.html.erb
<h1>New historia clinica</h1>

<%= render "form", historia_clinica: @historia_clinica %>

<br>

<div>
  <%= link_to "Back to historia clinicas", historia_clinicas_path %>
</div>

app/views/historia_clinicas/new_vacunae.html.erb
<%= form_with(model: @historia_clinica, url: create_vacunae_historia_clinicas_path) do |form| %>

  <div class="col-md-5">
  <%= form.label :fecha_de_atencion, style: "display: block;" %>
    <div class="input-group has-validation">
      <%= form.date_field :fecha, class: 'form-control', required: true, max: Date.today.to_s, style: 'appearance: none;' %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :marca, class: "form-label" %>
    <%= form.text_field :producto, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :lote, class: "form-label" %>
    <%= form.text_field :lote, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= label_tag 'historia_clinica[dosis]', 'Dosis (en mililitros)', class: "form-label" %>
    <%= form.number_field :dosis, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :detalle, class: "form-label" %>
    <%= form.text_area :detalle, class: "form-control" %>
  </div>

  <%= form.hidden_field :id, value: @perrito.id %>
  <%= form.hidden_field :tipo, value: 'Vacuna Anti Enfermedades' %>
  <%= form.hidden_field :tipoVacuna, value: 'vacunae' %>
  <%= form.hidden_field :quien, value: params[:quien] %>
  <%= form.hidden_field :user_id, value: params[:user_id] %>

  <div class="mb-3">
    <button type="button" class="btn btn-success" style='margin-block: 10px;' data-bs-toggle="modal" data-bs-target="#ModalRegistrar-<%= @perrito.id %>">
              Guardar
      </button>

      <!-- Modal Publicar-->
        <div class="modal fade" id="ModalRegistrar-<%= @perrito.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmar Registracion</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
                <div class="modal-body">
                  Confirma la registracion en la historia clinica ?
                </div>
              <div class="modal-footer">
                <%= form.submit 'Confirmar',  class: "btn btn-success", style:'margin: 2px' %>
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Atras</button>
              </div>
            </div>
          </div>
        </div>
    <% if params[:quien] == 'ajeno' %>
        <%= link_to "Atras", ver_perrito_ajeno_path(@perrito, user_id: @user.id) , class: "btn btn-danger", style:'margin-block: 10px;'%>
    <% else %>
        <%= link_to "Atras", ver_perrito_path(@perrito, user: current_user) , class: "btn btn-danger", style:'margin-block: 10px;'%>
    <% end %>
  </div>
<% end %>

app/views/historia_clinicas/new_vacunar.html.erb
<%= form_with(model: @historia_clinica, url: create_vacunar_historia_clinicas_path) do |form| %>

  <div class="col-md-5">
  <%= form.label :fecha_de_atencion, style: "display: block;" %>
    <div class="input-group has-validation">
      <%= form.date_field :fecha, class: 'form-control', required: true, max: Date.today.to_s, style: 'appearance: none;' %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :marca, class: "form-label" %>
    <%= form.text_field :producto, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :lote, class: "form-label" %>
    <%= form.text_field :lote, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= label_tag 'historia_clinica[dosis]', 'Dosis (en mililitros)', class: "form-label" %>
    <%= form.number_field :dosis, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :detalle, class: "form-label" %>
    <%= form.text_area :detalle, class: "form-control" %>
  </div>

  <%= form.hidden_field :id, value: @perrito.id %>
  <%= form.hidden_field :tipo, value: 'Vacuna Antirrábica' %>
  <%= form.hidden_field :tipoVacuna, value: 'vacunar' %>
  <%= form.hidden_field :quien, value: params[:quien] %>
  <%= form.hidden_field :user_id, value: params[:user_id] %>

  <div class="mb-3">
    <button type="button" class="btn btn-success" style='margin-block: 10px;' data-bs-toggle="modal" data-bs-target="#ModalRegistrar-<%= @perrito.id %>">
        Guardar
      </button>

      <!-- Modal Publicar-->
        <div class="modal fade" id="ModalRegistrar-<%= @perrito.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmar Registracion</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
                <div class="modal-body">
                  Confirma la registracion en la historia clinica ?
                </div>
              <div class="modal-footer">
                <%= form.submit 'Confirmar',  class: "btn btn-success", style:'margin: 2px' %>
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Atras</button>
              </div>
            </div>
          </div>
        </div>
    <% if params[:quien] == 'ajeno' %>
        <%= link_to "Atras", ver_perrito_ajeno_path(@perrito, user_id: @user.id) , class: "btn btn-danger", style:'margin-block: 10px;'%>
    <% else %>
        <%= link_to "Atras", ver_perrito_path(@perrito, user: current_user) , class: "btn btn-danger", style:'margin-block: 10px;'%>
    <% end %>
  </div>
<% end %>

app/views/historia_clinicas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @historia_clinica %>

<div>
  <%= link_to "Edit this historia clinica", edit_historia_clinica_path(@historia_clinica) %> |
  <%= link_to "Back to historia clinicas", historia_clinicas_path %>

  <%= button_to "Destroy this historia clinica", @historia_clinica, method: :delete %>
</div>

app/views/historia_clinicas/ver_atencion.html.erb
<div class="container mt-5">
<h2 style="margin-block: 20px;">Información de la Atención Clínica</h2>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Tipo</th>
        <td><%= @historia_clinica.tipo %></td>
      </tr>
      <tr>
        <th>Fecha de Atención</th>
        <td><%= "#{@historia_clinica.dia}/#{@historia_clinica.mes}/#{@historia_clinica.año}" %></td>
      </tr>
      <tr>
        <th>Cuadro Sintomatológico</th>
        <td><%= @historia_clinica.sintomas %></td>
      </tr>
      <tr>
        <th>Diagnóstico</th>
        <td><%= @historia_clinica.diagnostico %></td>
      </tr>
      <tr>
        <th>Tratamiento</th>
        <td><%= @historia_clinica.tratamiento %></td>
      </tr>
      <tr>
        <th>Detalles</th>
        <td><%= @historia_clinica.detalle %></td>
      </tr>
    </tbody>
  </table>


<% if params[:quien] == 'ajeno' %>
  <%= link_to "Volver atrás", ver_perrito_ajeno_path(@perrito, user_id: @user.id), class: "btn btn-secondary" %>
<% else %>
  <%= link_to "Volver atrás", ver_perrito_path(@perrito, user: current_user), class: "btn btn-secondary" %>
<% end %>